// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAWh2CkDDQ3yRyqoRQx8vpcVLJOKoKy8o',
    appId: '1:1029053162869:web:0952d6783c749a7b859f3c',
    messagingSenderId: '1029053162869',
    projectId: 'komfortplus-5b099',
    authDomain: 'komfortplus-5b099.firebaseapp.com',
    storageBucket: 'komfortplus-5b099.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkaAXOBLZUx1z3YYiSoI5_xSeEEnx-C7U',
    appId: '1:1029053162869:android:569ff673d40253ab859f3c',
    messagingSenderId: '1029053162869',
    projectId: 'komfortplus-5b099',
    storageBucket: 'komfortplus-5b099.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB74b7v4iptFTlwhDYssBxEDq-esvEbBO8',
    appId: '1:1029053162869:ios:c89576da6218480e859f3c',
    messagingSenderId: '1029053162869',
    projectId: 'komfortplus-5b099',
    storageBucket: 'komfortplus-5b099.appspot.com',
    androidClientId: '1029053162869-a9mhrg6epeuvq43btcatf80vfmqj7hdj.apps.googleusercontent.com',
    iosClientId: '1029053162869-o45841avpjbn35dvqqj3jn6r1iqk6j9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.komfortik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB74b7v4iptFTlwhDYssBxEDq-esvEbBO8',
    appId: '1:1029053162869:ios:c89576da6218480e859f3c',
    messagingSenderId: '1029053162869',
    projectId: 'komfortplus-5b099',
    storageBucket: 'komfortplus-5b099.appspot.com',
    androidClientId: '1029053162869-a9mhrg6epeuvq43btcatf80vfmqj7hdj.apps.googleusercontent.com',
    iosClientId: '1029053162869-o45841avpjbn35dvqqj3jn6r1iqk6j9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.komfortik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAWh2CkDDQ3yRyqoRQx8vpcVLJOKoKy8o',
    appId: '1:1029053162869:web:28d5003f9b7f0999859f3c',
    messagingSenderId: '1029053162869',
    projectId: 'komfortplus-5b099',
    authDomain: 'komfortplus-5b099.firebaseapp.com',
    storageBucket: 'komfortplus-5b099.appspot.com',
  );
}
